// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.jflex

/********************************** LEXER FILE ********************************/
// JAVA IMPORTS ----------------------------------------------------------------
package ymcris.compilers.flowchart.lexer;

import java_cup.runtime.*;
import java.util.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\126\u0100\1\u2600\1\u0100\1\u2700"+
    "\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\53\u0100\1\u2d00\10\u2e00"+
    "\31\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u5000\1\u5100\1\u5200"+
    "\3\u0100\1\u5300\1\u5400\1\u5500\11\u1f00\1\u5600\4\u0100\1\u5700"+
    "\16\u0100\1\u5800\2\u0100\1\u5900\32\u1f00\1\u5a00\6\u1f00\2\u0100"+
    "\1\u5b00\1\u5c00\1\u1f00\1\u5d00\1\u5e00\1\u5f00\27\u0100\1\u6000"+
    "\4\u0100\1\u6100\1\u6200\41\u1f00\1\u6300\1\u0100\1\u6400\1\u6500"+
    "\11\u1f00\1\u6600\17\u1f00\1\u6700\2\u1f00\1\u6800\1\u1f00\1\u6900"+
    "\1\u6a00\1\u1f00\1\u6b00\1\u6c00\1\u6d00\1\u6e00\2\u1f00\1\u6f00"+
    "\4\u1f00\1\u7000\1\u7100\1\u7200\1\u7300\1\u1f00\1\u7400\1\u7500"+
    "\1\u1f00\1\u7600\1\u7700\1\u7800\2\u1f00\1\u7900\1\u1f00\1\u7a00"+
    "\14\u1f00\1\u6700\4\u1f00\246\u0100\1\u7b00\20\u0100\1\u7c00\1\u7d00"+
    "\25\u0100\1\u7e00\34\u0100\1\u7f00\2\u0100\1\u8000\11\u1f00\2\u0100"+
    "\1\u8100\5\u1f00\23\u0100\1\u8200\17\u0100\1\u8300\u0adc\u1f00\1\u8400"+
    "\1\u8500\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\6\1\13\1\6"+
    "\1\14\1\15\1\16\1\17\1\6\1\20\1\21\1\22"+
    "\12\0\2\6\1\23\1\24\1\25\2\6\1\26\1\12"+
    "\1\27\1\30\1\31\1\32\1\12\1\33\1\34\3\12"+
    "\1\35\1\36\1\37\2\12\1\40\1\41\1\42\1\12"+
    "\1\43\4\12\1\6\1\44\2\6\1\12\1\6\6\12"+
    "\1\45\1\12\1\46\4\12\1\47\3\12\1\50\1\12"+
    "\1\51\6\12\1\6\1\52\2\6\6\0\1\53\32\0"+
    "\2\6\4\12\4\6\1\12\2\6\1\0\7\6\1\12"+
    "\4\6\1\12\5\6\27\12\1\6\37\12\1\6\u01ca\12"+
    "\4\6\14\12\16\6\5\12\7\6\1\12\1\6\1\12"+
    "\21\6\160\0\5\12\1\6\2\12\2\6\4\12\1\6"+
    "\1\12\6\6\1\12\1\6\3\12\1\6\1\12\1\6"+
    "\24\12\1\6\123\12\1\6\213\12\1\6\5\0\2\6"+
    "\246\12\1\6\46\12\2\6\1\12\6\6\51\12\6\6"+
    "\1\12\1\6\55\0\1\6\1\0\1\6\2\0\1\6"+
    "\2\0\1\6\1\0\10\6\33\12\4\6\4\12\15\6"+
    "\6\0\5\6\1\12\4\6\13\0\1\6\1\0\3\6"+
    "\53\12\37\0\4\6\2\12\1\0\143\12\1\6\1\12"+
    "\10\0\1\6\6\0\2\12\2\0\1\6\4\0\2\12"+
    "\12\0\3\12\2\6\1\12\17\6\1\0\1\12\1\0"+
    "\36\12\33\0\2\6\131\12\13\0\1\12\16\6\12\0"+
    "\41\12\11\0\2\12\4\6\1\12\2\6\1\0\30\12"+
    "\4\0\1\12\11\0\1\12\3\0\1\12\5\0\22\6"+
    "\31\12\3\0\4\6\13\12\5\6\30\12\1\6\6\12"+
    "\1\6\2\0\5\6\11\0\52\12\72\0\66\12\3\0"+
    "\1\12\22\0\1\12\7\0\12\12\2\0\2\6\12\0"+
    "\1\6\20\12\3\0\1\6\10\12\2\6\2\12\2\6"+
    "\26\12\1\6\7\12\1\6\1\12\3\6\4\12\2\6"+
    "\1\0\1\12\7\0\2\6\2\0\2\6\3\0\1\12"+
    "\10\6\1\0\4\6\2\12\1\6\3\12\2\0\2\6"+
    "\12\0\4\12\7\6\2\12\1\6\1\0\2\6\3\0"+
    "\1\6\6\12\4\6\2\12\2\6\26\12\1\6\7\12"+
    "\1\6\2\12\1\6\2\12\1\6\2\12\2\6\1\0"+
    "\1\6\5\0\4\6\2\0\2\6\3\0\3\6\1\0"+
    "\7\6\4\12\1\6\1\12\7\6\14\0\3\12\1\0"+
    "\13\6\3\0\1\6\11\12\1\6\3\12\1\6\26\12"+
    "\1\6\7\12\1\6\2\12\1\6\5\12\2\6\1\0"+
    "\1\12\10\0\1\6\3\0\1\6\3\0\2\6\1\12"+
    "\17\6\2\12\2\0\2\6\12\0\1\6\1\12\7\6"+
    "\1\12\6\0\1\6\3\0\1\6\10\12\2\6\2\12"+
    "\2\6\26\12\1\6\7\12\1\6\2\12\1\6\5\12"+
    "\2\6\1\0\1\12\7\0\2\6\2\0\2\6\3\0"+
    "\7\6\3\0\4\6\2\12\1\6\3\12\2\0\2\6"+
    "\12\0\1\6\1\12\20\6\1\0\1\12\1\6\6\12"+
    "\3\6\3\12\1\6\4\12\3\6\2\12\1\6\1\12"+
    "\1\6\2\12\3\6\2\12\3\6\3\12\3\6\14\12"+
    "\4\6\5\0\3\6\3\0\1\6\4\0\2\6\1\12"+
    "\6\6\1\0\16\6\12\0\11\6\1\12\6\6\5\0"+
    "\10\12\1\6\3\12\1\6\27\12\1\6\20\12\2\6"+
    "\1\0\1\12\7\0\1\6\3\0\1\6\4\0\7\6"+
    "\2\0\1\6\3\12\2\6\1\12\2\6\2\12\2\0"+
    "\2\6\12\0\20\6\1\12\3\0\1\6\10\12\1\6"+
    "\3\12\1\6\27\12\1\6\12\12\1\6\5\12\2\6"+
    "\1\0\1\12\7\0\1\6\3\0\1\6\4\0\7\6"+
    "\2\0\6\6\2\12\1\6\2\12\2\0\2\6\12\0"+
    "\1\6\2\12\1\0\14\6\4\0\11\12\1\6\3\12"+
    "\1\6\51\12\2\0\1\12\7\0\1\6\3\0\1\6"+
    "\4\0\1\12\5\6\3\12\1\0\7\6\3\12\2\0"+
    "\2\6\12\0\12\6\6\12\1\6\3\0\1\6\22\12"+
    "\3\6\30\12\1\6\11\12\1\6\1\12\2\6\7\12"+
    "\3\6\1\0\4\6\6\0\1\6\1\0\1\6\10\0"+
    "\6\6\12\0\2\6\2\0\15\6\60\12\1\0\2\12"+
    "\7\0\4\6\10\12\10\0\1\6\12\0\47\6\2\12"+
    "\1\6\1\12\1\6\5\12\1\6\30\12\1\6\1\12"+
    "\1\6\12\12\1\0\2\12\11\0\1\12\2\6\5\12"+
    "\1\6\1\12\1\6\7\0\1\6\12\0\2\6\4\12"+
    "\40\6\1\12\27\6\2\0\6\6\12\0\13\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\2\0\10\12\1\6"+
    "\44\12\4\6\24\0\1\6\2\0\5\12\13\0\1\6"+
    "\44\0\11\6\1\0\71\6\53\12\24\0\1\12\12\0"+
    "\6\6\6\12\4\0\4\12\3\0\1\12\3\0\2\12"+
    "\7\0\3\12\4\0\15\12\14\0\1\12\17\0\2\6"+
    "\46\12\1\6\1\12\5\6\1\12\2\6\53\12\1\6"+
    "\115\12\1\6\4\12\2\6\7\12\1\6\1\12\1\6"+
    "\4\12\2\6\51\12\1\6\4\12\2\6\41\12\1\6"+
    "\4\12\2\6\7\12\1\6\1\12\1\6\4\12\2\6"+
    "\17\12\1\6\71\12\1\6\4\12\2\6\103\12\2\6"+
    "\3\0\40\6\20\12\20\6\126\12\2\6\6\12\3\6"+
    "\u016c\12\2\6\21\12\1\6\32\12\5\6\113\12\3\6"+
    "\13\12\7\6\22\12\4\0\11\6\23\12\3\0\13\6"+
    "\22\12\2\0\14\6\15\12\1\6\3\12\1\6\2\0"+
    "\14\6\64\12\40\0\3\6\1\12\3\6\2\12\1\0"+
    "\2\6\12\0\41\6\17\0\6\6\131\12\7\6\5\12"+
    "\2\0\42\12\1\0\1\12\5\6\106\12\12\6\37\12"+
    "\1\6\14\0\4\6\14\0\12\6\12\0\36\12\2\6"+
    "\5\12\13\6\54\12\4\6\32\12\6\6\12\0\46\6"+
    "\27\12\5\0\4\6\65\12\12\0\1\6\35\0\2\6"+
    "\13\0\6\6\12\0\15\6\1\12\10\6\16\0\1\6"+
    "\20\0\61\6\5\0\57\12\21\0\10\12\3\6\12\0"+
    "\21\6\11\0\14\6\3\0\36\12\15\0\2\12\12\0"+
    "\54\12\16\0\14\6\44\12\24\0\10\6\12\0\3\6"+
    "\3\12\12\0\44\12\2\6\13\12\5\6\53\12\2\6"+
    "\3\12\20\6\3\0\1\6\25\0\4\12\1\0\6\12"+
    "\1\0\2\12\3\0\1\12\5\6\300\12\100\0\26\12"+
    "\2\6\6\12\2\6\46\12\2\6\6\12\2\6\10\12"+
    "\1\6\1\12\1\6\1\12\1\6\1\12\1\6\37\12"+
    "\2\6\65\12\1\6\7\12\1\6\1\12\3\6\3\12"+
    "\1\6\7\12\3\6\4\12\2\6\6\12\4\6\15\12"+
    "\5\6\3\12\1\6\7\12\16\6\5\0\30\6\2\3"+
    "\5\0\20\6\2\12\23\6\1\12\13\6\5\0\1\6"+
    "\12\0\1\6\1\12\15\6\1\12\20\6\15\12\3\6"+
    "\41\12\17\6\15\0\4\6\1\0\3\6\14\0\21\6"+
    "\1\12\4\6\1\12\2\6\12\12\1\6\1\12\3\6"+
    "\5\12\6\6\1\12\1\6\1\12\1\6\1\12\1\6"+
    "\4\12\1\6\13\12\2\6\4\12\5\6\5\12\4\6"+
    "\1\12\21\6\51\12\u0177\6\345\12\6\6\4\12\3\0"+
    "\2\12\14\6\46\12\1\6\1\12\5\6\1\12\2\6"+
    "\70\12\7\6\1\12\17\6\1\0\27\12\11\6\7\12"+
    "\1\6\7\12\1\6\7\12\1\6\7\12\1\6\7\12"+
    "\1\6\7\12\1\6\7\12\1\6\7\12\1\6\40\0"+
    "\57\6\1\12\325\6\3\12\31\6\11\12\6\0\1\6"+
    "\5\12\2\6\5\12\4\6\126\12\2\6\2\0\2\6"+
    "\3\12\1\6\132\12\1\6\4\12\5\6\53\12\1\6"+
    "\136\12\21\6\40\12\60\6\320\12\100\6\215\12\103\6"+
    "\56\12\2\6\15\12\3\6\20\12\12\0\2\12\24\6"+
    "\57\12\1\0\4\6\12\0\1\6\37\12\2\0\120\12"+
    "\2\0\45\6\11\12\2\6\147\12\2\6\103\12\2\6"+
    "\2\12\1\6\1\12\1\6\10\12\25\6\20\12\1\0"+
    "\3\12\1\0\4\12\1\0\27\12\5\0\4\6\1\0"+
    "\13\6\1\12\7\6\64\12\14\6\2\0\62\12\22\0"+
    "\12\6\12\0\6\6\22\0\6\12\3\6\1\12\1\6"+
    "\2\12\13\0\34\12\10\0\2\6\27\12\15\0\14\6"+
    "\35\12\3\6\4\0\57\12\16\0\16\6\1\12\12\0"+
    "\6\6\5\12\1\0\12\12\12\0\5\12\1\6\51\12"+
    "\16\0\11\6\3\12\1\0\10\12\2\0\2\6\12\0"+
    "\6\6\27\12\3\6\1\12\3\0\62\12\1\0\1\12"+
    "\3\0\2\12\2\0\5\12\2\0\1\12\1\0\1\12"+
    "\30\6\3\12\2\6\13\12\5\0\2\6\3\12\2\0"+
    "\12\6\6\12\2\6\6\12\2\6\6\12\11\6\7\12"+
    "\1\6\7\12\1\6\53\12\1\6\16\12\6\6\163\12"+
    "\10\0\1\6\2\0\2\6\12\0\6\6\244\12\14\6"+
    "\27\12\4\6\61\12\4\6\u0100\3\156\12\2\6\152\12"+
    "\46\6\7\12\14\6\5\12\5\6\1\12\1\0\12\12"+
    "\1\6\15\12\1\6\5\12\1\6\1\12\1\6\2\12"+
    "\1\6\2\12\1\6\154\12\41\6\153\12\22\6\100\12"+
    "\2\6\66\12\50\6\15\12\3\6\20\0\20\6\20\0"+
    "\3\6\2\12\30\6\3\12\31\6\1\12\6\6\5\12"+
    "\1\6\207\12\2\6\1\0\4\6\1\12\13\6\12\0"+
    "\7\6\32\12\4\6\1\12\1\6\32\12\13\6\131\12"+
    "\3\6\6\12\2\6\6\12\2\6\6\12\2\6\3\12"+
    "\3\6\2\12\3\6\2\12\22\6\3\0\4\6\14\12"+
    "\1\6\32\12\1\6\23\12\1\6\2\12\1\6\17\12"+
    "\2\6\16\12\42\6\173\12\105\6\65\12\210\6\1\0"+
    "\202\6\35\12\3\6\61\12\17\6\1\0\37\6\40\12"+
    "\15\6\36\12\5\6\46\12\5\0\5\6\36\12\2\6"+
    "\44\12\4\6\10\12\1\6\5\12\52\6\236\12\2\6"+
    "\12\0\6\6\44\12\4\6\44\12\4\6\50\12\10\6"+
    "\64\12\14\6\13\12\1\6\17\12\1\6\7\12\1\6"+
    "\2\12\1\6\13\12\1\6\17\12\1\6\7\12\1\6"+
    "\2\12\3\6\64\12\14\6\67\12\11\6\26\12\12\6"+
    "\10\12\30\6\6\12\1\6\52\12\1\6\11\12\105\6"+
    "\6\12\2\6\1\12\1\6\54\12\1\6\2\12\3\6"+
    "\1\12\2\6\27\12\12\6\27\12\11\6\37\12\101\6"+
    "\23\12\1\6\2\12\12\6\26\12\12\6\32\12\106\6"+
    "\70\12\6\6\2\12\100\6\1\12\3\0\1\6\2\0"+
    "\5\6\4\0\4\12\1\6\3\12\1\6\35\12\2\6"+
    "\3\0\4\6\1\0\40\6\35\12\3\6\35\12\43\6"+
    "\10\12\1\6\34\12\2\0\31\6\66\12\12\6\26\12"+
    "\12\6\23\12\15\6\22\12\156\6\111\12\67\6\63\12"+
    "\15\6\63\12\15\6\44\12\4\0\10\6\12\0\6\6"+
    "\12\0\34\12\3\6\5\0\1\6\27\12\372\6\52\12"+
    "\1\6\2\0\3\6\2\12\20\6\3\12\67\6\4\0"+
    "\35\12\12\6\1\12\10\6\26\12\13\0\37\6\22\12"+
    "\4\0\52\6\25\12\33\6\27\12\11\6\3\0\65\12"+
    "\17\0\37\6\13\0\2\12\2\0\1\12\11\6\4\0"+
    "\55\12\13\0\2\6\1\0\4\6\1\0\12\6\1\0"+
    "\2\6\31\12\7\6\12\0\6\6\3\0\44\12\16\0"+
    "\1\6\12\0\4\6\1\12\2\0\1\12\10\6\43\12"+
    "\1\0\2\6\1\12\11\6\3\0\60\12\16\0\4\12"+
    "\4\6\4\0\1\6\14\0\1\12\1\6\1\12\43\6"+
    "\22\12\1\6\31\12\14\0\6\6\1\0\2\12\1\0"+
    "\76\6\7\12\1\6\1\12\1\6\4\12\1\6\17\12"+
    "\1\6\12\12\7\6\57\12\14\0\5\6\12\0\6\6"+
    "\4\0\1\6\10\12\2\6\2\12\2\6\26\12\1\6"+
    "\7\12\1\6\2\12\1\6\5\12\1\6\2\0\1\12"+
    "\7\0\2\6\2\0\2\6\3\0\2\6\1\12\6\6"+
    "\1\0\5\6\5\12\2\0\2\6\7\0\3\6\5\0"+
    "\13\6\12\12\1\6\1\12\2\6\1\12\1\6\46\12"+
    "\1\6\1\12\11\0\1\6\1\0\2\6\1\0\1\6"+
    "\4\0\1\6\5\0\1\12\1\0\1\12\15\6\2\0"+
    "\35\6\65\12\22\0\4\12\5\6\12\0\4\6\1\0"+
    "\3\12\36\6\60\12\24\0\2\12\1\6\1\12\10\6"+
    "\12\0\246\6\57\12\7\0\2\6\11\0\27\6\4\12"+
    "\2\0\42\6\60\12\21\0\3\6\1\12\13\6\12\0"+
    "\46\6\53\12\15\0\1\12\7\6\12\0\6\6\24\0"+
    "\34\6\33\12\2\6\17\0\4\6\12\0\6\6\7\12"+
    "\271\6\54\12\17\0\145\6\100\12\12\0\25\6\10\12"+
    "\2\6\1\12\2\6\10\12\1\6\2\12\1\6\30\12"+
    "\6\0\1\6\2\0\2\6\4\0\1\12\1\0\1\12"+
    "\2\0\14\6\12\0\106\6\10\12\2\6\47\12\7\0"+
    "\2\6\7\0\1\12\1\6\1\12\1\0\33\6\1\12"+
    "\12\0\50\12\7\0\1\12\4\0\10\6\1\0\10\6"+
    "\1\12\13\0\56\12\20\0\3\6\1\12\22\6\111\12"+
    "\307\6\41\12\17\6\12\0\6\6\11\12\1\6\45\12"+
    "\10\0\1\6\10\0\1\12\17\6\12\0\30\6\36\12"+
    "\2\6\26\0\1\6\16\0\111\6\7\12\1\6\2\12"+
    "\1\6\46\12\6\0\3\6\1\0\1\6\2\0\1\6"+
    "\7\0\1\12\1\0\10\6\12\0\6\6\6\12\1\6"+
    "\2\12\1\6\40\12\5\0\1\6\2\0\1\6\5\0"+
    "\1\12\7\6\12\0\u0136\6\23\12\4\0\11\6\2\0"+
    "\1\12\1\0\15\12\1\6\42\12\7\0\3\6\5\0"+
    "\15\6\13\0\125\6\1\12\54\6\4\12\37\6\232\12"+
    "\146\6\157\12\21\6\304\12\u014c\6\141\12\17\6\60\12"+
    "\21\0\6\12\17\0\12\6\u019b\12\5\6\107\12\271\6"+
    "\36\12\34\0\306\6\71\12\7\6\37\12\1\6\12\0"+
    "\6\6\117\12\1\6\12\0\6\6\36\12\2\6\5\0"+
    "\13\6\60\12\7\0\11\6\4\12\14\6\12\0\11\6"+
    "\25\12\5\6\23\12\260\6\55\12\3\6\12\0\306\6"+
    "\100\12\200\6\113\12\4\6\1\0\1\12\67\0\7\6"+
    "\4\0\15\12\100\6\2\12\1\6\1\12\1\0\13\6"+
    "\2\0\16\6\370\12\10\6\326\12\51\6\12\12\u01e7\6"+
    "\4\12\1\6\7\12\1\6\2\12\1\6\43\12\17\6"+
    "\1\12\35\6\3\12\2\6\1\12\16\6\4\12\10\6"+
    "\u018c\12\4\6\153\12\5\6\15\12\3\6\11\12\7\6"+
    "\12\12\3\6\2\0\1\6\4\0\u014c\6\12\0\6\6"+
    "\56\0\2\6\27\0\u011e\6\5\0\3\6\26\0\2\6"+
    "\7\0\36\6\4\0\224\6\3\0\273\6\125\12\1\6"+
    "\107\12\1\6\2\12\2\6\1\12\2\6\2\12\2\6"+
    "\4\12\1\6\14\12\1\6\1\12\1\6\7\12\1\6"+
    "\101\12\1\6\4\12\2\6\10\12\1\6\7\12\1\6"+
    "\34\12\1\6\4\12\1\6\5\12\1\6\1\12\3\6"+
    "\7\12\1\6\u0154\12\2\6\31\12\1\6\31\12\1\6"+
    "\37\12\1\6\31\12\1\6\37\12\1\6\31\12\1\6"+
    "\37\12\1\6\31\12\1\6\37\12\1\6\31\12\1\6"+
    "\10\12\2\6\151\0\4\6\62\0\10\6\1\0\16\6"+
    "\1\0\26\6\5\0\1\6\17\0\120\6\37\12\6\6"+
    "\6\12\325\6\7\0\1\6\21\0\2\6\7\0\1\6"+
    "\2\0\1\6\5\0\5\6\76\12\41\6\1\0\160\6"+
    "\55\12\3\6\7\0\7\12\2\6\12\0\4\6\1\12"+
    "\u0141\6\36\12\1\0\21\6\54\12\16\0\5\6\1\12"+
    "\320\6\34\12\16\0\326\6\36\12\2\0\1\12\12\0"+
    "\345\6\7\12\1\6\4\12\1\6\2\12\1\6\17\12"+
    "\1\6\305\12\13\6\7\0\51\6\104\12\7\0\1\12"+
    "\4\6\12\0\u0156\6\1\12\117\6\4\12\1\6\33\12"+
    "\1\6\2\12\1\6\1\12\2\6\1\12\1\6\12\12"+
    "\1\6\4\12\1\6\1\12\1\6\1\12\6\6\1\12"+
    "\4\6\1\12\1\6\1\12\1\6\1\12\1\6\3\12"+
    "\1\6\2\12\1\6\1\12\2\6\1\12\1\6\1\12"+
    "\1\6\1\12\1\6\1\12\1\6\1\12\1\6\2\12"+
    "\1\6\1\12\2\6\4\12\1\6\7\12\1\6\4\12"+
    "\1\6\4\12\1\6\1\12\1\6\12\12\1\6\21\12"+
    "\5\6\3\12\1\6\5\12\1\6\21\12\104\6\340\12"+
    "\40\6\72\12\6\6\336\12\2\6\u0182\12\16\6\u0131\12"+
    "\17\6\156\12\242\6\36\12\342\6\113\12\5\6\u0160\12"+
    "\121\6\1\0\36\6\140\0\200\6\360\0\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[34304];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\10\6\1\1\1\20\1\21\1\22\1\0\1\2"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\7\6\1\31"+
    "\1\6\1\32\1\33\1\34\1\35\1\36\1\37\2\6"+
    "\1\40\4\6\1\41\10\6\1\42\2\6\1\43\1\44"+
    "\3\6\1\0\2\6\1\45\2\6\1\0\3\6\1\46"+
    "\1\0\1\47\1\6\1\50\1\0\1\6\1\0\1\6"+
    "\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\204\0\204"+
    "\0\u0108\0\u0134\0\204\0\204\0\204\0\204\0\204\0\204"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\204\0\204\0\u039c"+
    "\0\204\0\204\0\204\0\204\0\204\0\204\0\204\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u0108\0\u04fc"+
    "\0\204\0\204\0\204\0\204\0\204\0\204\0\u0528\0\u0554"+
    "\0\u0580\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u0108\0\u065c\0\u0688"+
    "\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8"+
    "\0\u0814\0\u0108\0\u0108\0\u0840\0\u086c\0\u0898\0\u08c4\0\u08f0"+
    "\0\u091c\0\u0108\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24"+
    "\0\u0108\0\u0a50\0\u0108\0\u0a7c\0\u0108\0\u0aa8\0\u0ad4\0\u0b00"+
    "\0\u0b2c\0\u08c4\0\u0108";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\2\5\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\4"+
    "\1\20\1\21\1\22\1\23\2\11\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\3\11\1\32\1\11\1\33\1\4"+
    "\5\11\1\34\1\0\2\35\1\36\2\35\1\0\2\35"+
    "\1\37\33\35\1\40\7\35\2\41\1\42\3\0\45\41"+
    "\56\0\2\5\1\0\2\5\72\0\1\43\27\0\1\11"+
    "\11\0\1\11\13\0\16\11\1\0\5\11\1\0\1\11"+
    "\13\0\1\44\64\0\1\45\53\0\1\46\53\0\1\47"+
    "\27\0\1\11\11\0\1\11\13\0\16\11\1\0\1\11"+
    "\1\50\3\11\1\0\2\11\11\0\1\11\13\0\10\11"+
    "\1\51\5\11\1\0\5\11\1\0\2\11\11\0\1\11"+
    "\13\0\6\11\1\52\7\11\1\0\5\11\1\0\2\11"+
    "\11\0\1\11\13\0\1\53\15\11\1\0\5\11\1\0"+
    "\2\11\11\0\1\11\13\0\10\11\1\54\5\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\6\11\1\55"+
    "\2\11\1\56\4\11\1\0\5\11\1\0\2\11\11\0"+
    "\1\11\13\0\6\11\1\57\7\11\1\0\5\11\1\0"+
    "\2\11\11\0\1\11\13\0\1\60\15\11\1\0\5\11"+
    "\1\0\1\11\52\0\1\61\1\0\2\35\1\0\2\35"+
    "\1\0\2\35\1\0\33\35\1\0\7\35\10\0\1\62"+
    "\33\0\1\63\2\0\1\64\1\65\1\66\2\0\1\11"+
    "\11\0\1\11\13\0\16\11\1\0\1\67\4\11\1\0"+
    "\2\11\11\0\1\11\13\0\14\11\1\70\1\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\10\11\1\71"+
    "\5\11\1\0\5\11\1\0\2\11\11\0\1\11\13\0"+
    "\1\11\1\72\14\11\1\0\5\11\1\0\2\11\11\0"+
    "\1\11\13\0\6\11\1\73\7\11\1\0\5\11\1\0"+
    "\2\11\11\0\1\11\13\0\3\11\1\74\12\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\13\11\1\75"+
    "\2\11\1\0\5\11\1\0\2\11\11\0\1\11\13\0"+
    "\12\11\1\76\3\11\1\0\5\11\1\0\2\11\11\0"+
    "\1\11\13\0\16\11\1\0\1\11\1\77\3\11\1\0"+
    "\2\11\11\0\1\11\13\0\11\11\1\100\4\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\7\11\1\101"+
    "\3\11\1\102\2\11\1\0\5\11\1\0\2\11\11\0"+
    "\1\11\13\0\3\11\1\103\12\11\1\0\5\11\1\0"+
    "\2\11\11\0\1\11\13\0\1\11\1\104\14\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\10\11\1\105"+
    "\5\11\1\0\5\11\1\0\2\11\11\0\1\11\13\0"+
    "\14\11\1\106\1\11\1\0\5\11\1\0\2\11\11\0"+
    "\1\11\13\0\16\11\1\0\4\11\1\107\1\0\2\11"+
    "\11\0\1\11\13\0\10\11\1\110\5\11\1\0\5\11"+
    "\1\0\2\11\11\0\1\11\13\0\6\11\1\111\7\11"+
    "\1\0\5\11\1\0\2\11\11\0\1\11\13\0\6\11"+
    "\1\112\7\11\1\0\5\11\1\0\2\11\11\0\1\11"+
    "\13\0\12\11\1\113\3\11\1\0\5\11\1\0\2\11"+
    "\11\0\1\11\13\0\6\11\1\114\7\11\1\0\5\11"+
    "\1\0\2\11\11\0\1\11\13\0\14\11\1\115\1\11"+
    "\1\0\5\11\1\0\2\11\11\0\1\11\13\0\12\11"+
    "\1\116\3\11\1\0\5\11\1\0\2\11\11\0\1\11"+
    "\6\0\1\117\4\0\2\11\1\24\13\11\1\0\5\11"+
    "\1\0\2\11\11\0\1\11\13\0\1\11\1\120\14\11"+
    "\1\0\5\11\1\0\2\11\11\0\1\11\13\0\3\11"+
    "\1\121\12\11\1\0\5\11\1\0\2\11\11\0\1\11"+
    "\13\0\11\11\1\122\4\11\1\0\5\11\1\0\2\11"+
    "\11\0\1\11\13\0\12\11\1\123\3\11\1\0\5\11"+
    "\1\0\2\11\11\0\1\11\13\0\1\124\15\11\1\0"+
    "\5\11\1\0\1\11\30\0\1\125\23\0\1\11\11\0"+
    "\1\11\13\0\3\11\1\126\12\11\1\0\5\11\1\0"+
    "\2\11\11\0\1\11\13\0\10\11\1\127\5\11\1\0"+
    "\5\11\1\0\2\11\11\0\1\11\13\0\1\130\15\11"+
    "\1\0\5\11\1\0\2\11\11\0\1\11\13\0\12\11"+
    "\1\131\3\11\1\0\5\11\1\0\1\11\46\0\1\132"+
    "\5\0\1\11\11\0\1\11\13\0\13\11\1\133\2\11"+
    "\1\0\5\11\1\0\2\11\11\0\1\11\13\0\14\11"+
    "\1\134\1\11\1\0\5\11\1\0\2\11\11\0\1\11"+
    "\13\0\13\11\1\135\2\11\1\0\5\11\1\0\1\11"+
    "\45\0\1\136\6\0\1\11\11\0\1\11\13\0\12\11"+
    "\1\137\3\11\1\0\5\11\1\0\1\11\46\0\1\140"+
    "\5\0\1\11\11\0\1\11\13\0\1\141\15\11\1\0"+
    "\5\11\1\0\1\11\51\0\1\142\2\0\1\11\11\0"+
    "\1\11\13\0\13\11\1\143\2\11\1\0\5\11\1\0"+
    "\1\11";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2904];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\2\11\2\1\6\11\15\1\2\11"+
    "\1\0\7\11\11\1\6\11\30\1\1\0\5\1\1\0"+
    "\4\1\1\0\3\1\1\0\1\1\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    // REFERENCE VARIABLES -----------------------------------------------------
    StringBuffer buffer;
    private List<String> errorList;

    // SPECIFIC METHODS --------------------------------------------------------
    // ERROR REPORT
    private void error(String message){
         errorList.add("Error in line: " + (yyline+1) + ", column: " +
         (yycolumn+1) + " : " + message);
    }

     // PARSER METHDOS
    private Symbol symbol(int type){
        return new Symbol(type, yyline+1, yycolumn+1);
    }
    
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }

    // GETTERS -----------------------------------------------------------------
    public List<String> getLexicalErrors(){
        return this.errorList;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      
    buffer = new StringBuffer();
    errorList = new ArrayList<>();

    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              error("Unclosed string at EOF");
                        return symbol(sym.EOF);
            }  // fall though
            case 100: break;
            case COMMENT: {
              error("Unclosed comment at EOF");
                        return symbol(sym.EOF);
            }  // fall though
            case 101: break;
            default:
              {
                return symbol(sym.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error("Lexical error: " + yytext());
                        return symbol(sym.ERROR, yytext());
            }
          // fall through
          case 43: break;
          case 2:
            { /* IGNORE */
            }
          // fall through
          case 44: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 45: break;
          case 4:
            { buffer.setLength(0); yybegin(STRING);
            }
          // fall through
          case 46: break;
          case 5:
            { yybegin(COMMENT);
            }
          // fall through
          case 47: break;
          case 6:
            { return symbol(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 48: break;
          case 7:
            { return symbol(sym.OPEN_PARENT);
            }
          // fall through
          case 49: break;
          case 8:
            { return symbol(sym.CLOSED_PARENT);
            }
          // fall through
          case 50: break;
          case 9:
            { return symbol(sym.MULTIPLY);
            }
          // fall through
          case 51: break;
          case 10:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 52: break;
          case 11:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 53: break;
          case 12:
            { return symbol(sym.DIVIDE);
            }
          // fall through
          case 54: break;
          case 13:
            { return symbol(sym.LESS);
            }
          // fall through
          case 55: break;
          case 14:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 56: break;
          case 15:
            { return symbol(sym.GREATER);
            }
          // fall through
          case 57: break;
          case 16:
            { buffer.append( yytext() );
            }
          // fall through
          case 58: break;
          case 17:
            { error("Unclosed string literal");
                        yybegin(YYINITIAL);
                        return symbol(sym.ERROR);
            }
          // fall through
          case 59: break;
          case 18:
            { yybegin(YYINITIAL);
                        return symbol(sym.STRING, buffer.toString());
            }
          // fall through
          case 60: break;
          case 19:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 61: break;
          case 20:
            { return symbol(sym.DIFERENT);
            }
          // fall through
          case 62: break;
          case 21:
            { return symbol(sym.AND);
            }
          // fall through
          case 63: break;
          case 22:
            { return symbol(sym.LOE);
            }
          // fall through
          case 64: break;
          case 23:
            { return symbol(sym.EQUAL);
            }
          // fall through
          case 65: break;
          case 24:
            { return symbol(sym.GOE);
            }
          // fall through
          case 66: break;
          case 25:
            { return symbol(sym.IF);
            }
          // fall through
          case 67: break;
          case 26:
            { return symbol(sym.OR);
            }
          // fall through
          case 68: break;
          case 27:
            { buffer.append('\"');
            }
          // fall through
          case 69: break;
          case 28:
            { buffer.append('\\');
            }
          // fall through
          case 70: break;
          case 29:
            { buffer.append('\n');
            }
          // fall through
          case 71: break;
          case 30:
            { buffer.append('\r');
            }
          // fall through
          case 72: break;
          case 31:
            { buffer.append('\t');
            }
          // fall through
          case 73: break;
          case 32:
            { return symbol(sym.END);
            }
          // fall through
          case 74: break;
          case 33:
            { return symbol(sym.VAR);
            }
          // fall through
          case 75: break;
          case 34:
            { return symbol(sym.INTEGER, Integer.parseInt(yytext()));
            }
          // fall through
          case 76: break;
          case 35:
            { return symbol(sym.IF_END);
            }
          // fall through
          case 77: break;
          case 36:
            { return symbol(sym.DO);
            }
          // fall through
          case 78: break;
          case 37:
            { return symbol(sym.START);
            }
          // fall through
          case 79: break;
          case 38:
            { return symbol(sym.SHOW);
            }
          // fall through
          case 80: break;
          case 39:
            { return symbol(sym.THEN);
            }
          // fall through
          case 81: break;
          case 40:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 82: break;
          case 41:
            { return symbol(sym.DOUBLE, Double.parseDouble(yytext()));
            }
          // fall through
          case 83: break;
          case 42:
            { return symbol(sym.WHILE_END);
            }
          // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
