
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ymcris.pkmforms.form.creation.analyzer.parser;

/** CUP generated class containing symbol constants. */
public class CreationFormSym {
  /* terminals */
  public static final int HORIZONTAL = 42;
  public static final int SELECT_QUESTION = 62;
  public static final int IDENTIFIER = 82;
  public static final int TEXT_SIZE = 50;
  public static final int THIRD = 67;
  public static final int TABLE = 44;
  public static final int NUMBER_VARIABLE = 8;
  public static final int TWO_POINTS = 37;
  public static final int DOUBLE_BORDER = 58;
  public static final int SANS_SERIF = 53;
  public static final int DROP_QUESTION = 61;
  public static final int SECOND = 66;
  public static final int CLOSED_PARENT = 31;
  public static final int COMMA = 36;
  public static final int ELEMENTS = 43;
  public static final int DRAW = 11;
  public static final int LINE_BORDER = 56;
  public static final int OPEN_QUESTION = 60;
  public static final int FIRST = 65;
  public static final int INTEGER = 79;
  public static final int CLOSED_CURLY_BRACKETS = 35;
  public static final int BACKGROUND_COLOR = 49;
  public static final int OPEN_SQR_BRACKETS = 32;
  public static final int NOT = 29;
  public static final int TEXT = 45;
  public static final int STRING_VARIABLE = 9;
  public static final int WIDTH = 12;
  public static final int OPEN_PARENT = 30;
  public static final int SMILE = 72;
  public static final int STAR_NUMBER = 77;
  public static final int STYLES = 47;
  public static final int MULTIPLY = 16;
  public static final int NUMBER = 80;
  public static final int LOE = 23;
  public static final int HEART = 75;
  public static final int CURSIVE = 54;
  public static final int MONO = 52;
  public static final int PLUS = 14;
  public static final int DIVIDE = 17;
  public static final int SAD = 73;
  public static final int WHILE = 5;
  public static final int EQUAL = 20;
  public static final int MODULE = 19;
  public static final int DIFERENT = 21;
  public static final int FIFTH = 69;
  public static final int ASSIGN = 26;
  public static final int ELSE_IF = 3;
  public static final int OPEN_CURLY_BRACKETS = 34;
  public static final int DO = 6;
  public static final int FOR = 7;
  public static final int STAR = 76;
  public static final int GREATER = 24;
  public static final int DOTTED_BORDER = 57;
  public static final int ORIENTATION = 40;
  public static final int ELSE = 4;
  public static final int GOE = 22;
  public static final int MULTIPLE_QUESTION = 63;
  public static final int CORRECT = 70;
  public static final int CONTENT = 46;
  public static final int EOF = 0;
  public static final int EXPO = 18;
  public static final int VERTICAL = 41;
  public static final int SERIOUS = 74;
  public static final int LABEL = 59;
  public static final int MINUS = 15;
  public static final int FOURTH = 68;
  public static final int OR = 28;
  public static final int error = 1;
  public static final int POINT_Y = 39;
  public static final int IF = 2;
  public static final int POINT_X = 38;
  public static final int COLOR = 48;
  public static final int BORDER = 55;
  public static final int HEIGHT = 13;
  public static final int CLOSED_SQR_BRACKETS = 33;
  public static final int FONT_FAMILY = 51;
  public static final int CAT = 78;
  public static final int STRING = 81;
  public static final int LESS = 25;
  public static final int OPTIONS = 64;
  public static final int AND = 27;
  public static final int SPECIAL_VARIABLE = 10;
  public static final int WHO_IS_THAT_POKEMON = 71;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE_IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "NUMBER_VARIABLE",
  "STRING_VARIABLE",
  "SPECIAL_VARIABLE",
  "DRAW",
  "WIDTH",
  "HEIGHT",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "EXPO",
  "MODULE",
  "EQUAL",
  "DIFERENT",
  "GOE",
  "LOE",
  "GREATER",
  "LESS",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "OPEN_PARENT",
  "CLOSED_PARENT",
  "OPEN_SQR_BRACKETS",
  "CLOSED_SQR_BRACKETS",
  "OPEN_CURLY_BRACKETS",
  "CLOSED_CURLY_BRACKETS",
  "COMMA",
  "TWO_POINTS",
  "POINT_X",
  "POINT_Y",
  "ORIENTATION",
  "VERTICAL",
  "HORIZONTAL",
  "ELEMENTS",
  "TABLE",
  "TEXT",
  "CONTENT",
  "STYLES",
  "COLOR",
  "BACKGROUND_COLOR",
  "TEXT_SIZE",
  "FONT_FAMILY",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "BORDER",
  "LINE_BORDER",
  "DOTTED_BORDER",
  "DOUBLE_BORDER",
  "LABEL",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "OPTIONS",
  "FIRST",
  "SECOND",
  "THIRD",
  "FOURTH",
  "FIFTH",
  "CORRECT",
  "WHO_IS_THAT_POKEMON",
  "SMILE",
  "SAD",
  "SERIOUS",
  "HEART",
  "STAR",
  "STAR_NUMBER",
  "CAT",
  "INTEGER",
  "NUMBER",
  "STRING",
  "IDENTIFIER"
  };
}

