
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ymcris.pkmforms.form.creation.analyzer.parser;

import java.util.*;
import java_cup.runtime.*;
import ymcris.pkmforms.analyzer.ast.Node;
import ymcris.pkmforms.analyzer.ast.NodeType;
import ymcris.pkmforms.analyzer.tokens.errors.ErrorType;
import ymcris.pkmforms.analyzer.tokens.errors.ErrorToken;
import ymcris.pkmforms.analyzer.symbols.table.SymbolTable;
import ymcris.pkmforms.form.creation.analyzer.lexer.FormCreationLexer;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CreationFormParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return CreationFormSym.class;
}

  /** Default constructor. */
  @Deprecated
  public CreationFormParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CreationFormParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CreationFormParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\002\002\000\002\002\003\000\002\003\004" +
    "\000\002\003\004\000\002\004\006\000\002\004\006\000" +
    "\002\005\005\000\002\005\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\012\002\ufffe\012\011\013\012\124\010\001" +
    "\002\000\004\002\024\001\002\000\004\002\uffff\001\002" +
    "\000\004\002\000\001\002\000\004\002\ufffd\001\002\000" +
    "\004\034\021\001\002\000\004\124\016\001\002\000\004" +
    "\124\013\001\002\000\006\002\ufffb\034\014\001\002\000" +
    "\002\001\002\000\004\002\ufff9\001\002\000\006\002\ufffc" +
    "\034\017\001\002\000\002\001\002\000\004\002\ufffa\001" +
    "\002\000\002\001\002\000\004\002\ufff8\001\002\000\004" +
    "\002\ufff7\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\012\002\003\003\005\004\004\005\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\006\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\030\017\001" +
    "\001\000\002\001\001\000\006\006\022\030\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CreationFormParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CreationFormParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CreationFormParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    // REFERENCE VARIABLES -----------------------------------------------------
    private SymbolTable table;
    private FormCreationLexer lexer;
    private List<ErrorToken> errorList;

    // CONSTRUCTOR METHOD ------------------------------------------------------
    /**
     * Lexer and parser connection and error list connection
     */
    public CreationFormParser(FormCreationLexer lexer){
        super(lexer);
        
        this.table = lexer.getTable();
        this.errorList = lexer.getLexicalErrors();
    }

    // OVERRIDE METHODS --------------------------------------------------------
    @Override
    public void report_error(String message, Object info) {
        try{
            Symbol cur_token = (Symbol) info;

            StringBuilder builder= new StringBuilder();

            builder.append("Symbol: ");
            builder.append(symbl_name_from_id(cur_token.sym));
            
            if(cur_token != null){
                builder.append(", Lexeme: ");
                builder.append(cur_token.value);
            }

            if(message != null){
                builder.append(", Info: ");
                builder.append(message);
            }
            
            errorList.add(new ErrorToken(
                cur_token.value.toString(),// Lexeme?
                builder.toString(),
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));

        } catch (Exception e){
           System.out.println("Erroooooooooooooooor");
        }
    }

    @Override
    public void syntax_error(Symbol cur_token) {
        System.err.println("Unexpected token at line " 
            + cur_token.left + ", column " + cur_token.right);

        StringBuilder mssBuilder = new StringBuilder();

        String lexeme = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        mssBuilder.append(symbl_name_from_id(cur_token.sym));
        
        if(cur_token.value != null) {
            mssBuilder.append(cur_token.value.toString());
        }

        mssBuilder.append(", line: ");
        mssBuilder.append(cur_token.left);
        mssBuilder.append(", col: ");
        mssBuilder.append(cur_token.right);
        
        if( expected_token_ids().isEmpty()  ){
            mssBuilder.append(" -- ya no se esperaba ningun simbolo");
        } else {
            mssBuilder.append("Se esperaba: ");
            for(Integer expected_token_id : expected_token_ids() ){ 
                if(!symbl_name_from_id(expected_token_id).equals("error")){
                    mssBuilder.append(symbl_name_from_id(expected_token_id));
                    mssBuilder.append(" ");
                }
            }
        }

            errorList.add(new ErrorToken(
                lexeme,
                mssBuilder.toString(),
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));

        System.err.println(mssBuilder.toString() + " in line: " + cur_token.left);
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token){
        System.out.println("Tronó, ya perdíste");
        String lexeme = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);

           errorList.add(new ErrorToken(
                lexeme,
                "Unrecovered error :(",
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));
    }


    // GETTERS -----------------------------------------------------------------
    public FormCreationLexer getLexer(){
        return this.lexer;
    }

    public SymbolTable getTable(){
        return this.table;
    }    

    public List<ErrorToken> getErrorList(){
        return this.errorList;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CreationFormParser$actions {
  private final CreationFormParser parser;

  /** Constructor */
  CUP$CreationFormParser$actions(CreationFormParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CreationFormParser$do_action_part00000000(
    int                        CUP$CreationFormParser$act_num,
    java_cup.runtime.lr_parser CUP$CreationFormParser$parser,
    java.util.Stack            CUP$CreationFormParser$stack,
    int                        CUP$CreationFormParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CreationFormParser$result;

      /* select the action based on the action number */
      switch (CUP$CreationFormParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= pkm_forms EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)).right;
		Node start_val = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)).value;
		RESULT = start_val;
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CreationFormParser$parser.done_parsing();
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // pkm_forms ::= var_declaration 
            {
              Node RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node v1 = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		
            RESULT = v1;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("pkm_forms",0, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // pkm_forms ::= var_initialization 
            {
              Node RESULT =null;
		int v2left = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node v2 = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		
            RESULT = v2;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("pkm_forms",0, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // pkm_forms ::= 
            {
              Node RESULT =null;

              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("pkm_forms",0, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // pkm_forms ::= var_assignment 
            {
              Node RESULT =null;
		int v3left = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int v3right = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node v3 = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		
            RESULT = v3;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("pkm_forms",0, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // var_declaration ::= NUMBER_VARIABLE IDENTIFIER 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // number x

            Node node = new Node(NodeType.VAR_DECLARATION, null);

            node.addChild(new Node(NodeType.TYPE_NUMBER, null)); //number
            node.addChild(new Node(NodeType.ID, id)); //x

            RESULT = node;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_declaration",1, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= STRING_VARIABLE IDENTIFIER 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // string name

            Node node = new Node(NodeType.VAR_DECLARATION, null);

            node.addChild(new Node(NodeType.TYPE_STRING, null)); //string
            node.addChild(new Node(NodeType.ID, id)); //name

            RESULT = node;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_declaration",1, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-1)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_initialization ::= NUMBER_VARIABLE IDENTIFIER ASSIGN arithmetic_expr 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node e = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // number myHeight = 20.10

            Node node = new Node(NodeType.VAR_INITIALIZATION, null);

            node.addChild(new Node(NodeType.TYPE_NUMBER, null)); // number
            node.addChild(new Node(NodeType.ID, id)); // myHeight
            node.addChild(new Node(NodeType.ASSIGN, null)); // =
            node.addChild(e); // 20.10

            RESULT = node;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_initialization",2, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-3)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // var_initialization ::= STRING_VARIABLE IDENTIFIER ASSIGN general_string 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node s = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // string name = "Toribio"

            Node node = new Node(NodeType.VAR_INITIALIZATION, null);

            node.addChild(new Node(NodeType.TYPE_STRING, null)); // string
            node.addChild(new Node(NodeType.ID, id)); // name
            node.addChild(new Node(NodeType.ASSIGN, null)); // =
            node.addChild(s); // "Toribio"

            RESULT = node;

        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_initialization",2, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-3)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // var_assignment ::= IDENTIFIER ASSIGN arithmetic_expr 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node e = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // x = 10
            
            Node node = new Node(NodeType.VAR_ASSIGNMENT, null);
            
            node.addChild(new Node(NodeType.ID, id)); // x
            node.addChild(new Node(NodeType.ASSIGN, null)); // = 
            node.addChild(e); // 10
            
            RESULT = node;
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_assignment",3, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // var_assignment ::= IDENTIFIER ASSIGN general_string 
            {
              Node RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()).right;
		Node s = (Node)((java_cup.runtime.Symbol) CUP$CreationFormParser$stack.peek()).value;
		 // x = "PEPE"
            
            Node node = new Node(NodeType.VAR_ASSIGNMENT, null);
            
            node.addChild(new Node(NodeType.ID, id)); // x
            node.addChild(new Node(NodeType.ASSIGN, null)); // = 
            node.addChild(s); // 10
            
            RESULT = node;
            
        
              CUP$CreationFormParser$result = parser.getSymbolFactory().newSymbol("var_assignment",3, ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.elementAt(CUP$CreationFormParser$top-2)), ((java_cup.runtime.Symbol)CUP$CreationFormParser$stack.peek()), RESULT);
            }
          return CUP$CreationFormParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CreationFormParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CreationFormParser$do_action(
    int                        CUP$CreationFormParser$act_num,
    java_cup.runtime.lr_parser CUP$CreationFormParser$parser,
    java.util.Stack            CUP$CreationFormParser$stack,
    int                        CUP$CreationFormParser$top)
    throws java.lang.Exception
    {
              return CUP$CreationFormParser$do_action_part00000000(
                               CUP$CreationFormParser$act_num,
                               CUP$CreationFormParser$parser,
                               CUP$CreationFormParser$stack,
                               CUP$CreationFormParser$top);
    }
}

}
