/********************************** CUP FILE **********************************/
// JAVA IMPORTS ----------------------------------------------------------------
package ymcris.pkmforms.form.creation.analyzer.parser;

// CUP
import java.util.*;
import java_cup.runtime.*;

// AST CREATION
import ymcris.pkmforms.analyzer.ast.Node;
import ymcris.pkmforms.analyzer.ast.NodeType;

// TOKENS
import ymcris.pkmforms.analyzer.tokens.errors.ErrorType;
import ymcris.pkmforms.analyzer.tokens.errors.ErrorToken;

// SYMBOL TABLE
import ymcris.pkmforms.analyzer.symbols.table.SymbolTable;

// LEXER
import ymcris.pkmforms.form.creation.analyzer.lexer.FormCreationLexer;

/******************************** PARSER CODE *********************************/
parser code {:

    // REFERENCE VARIABLES -----------------------------------------------------
    private SymbolTable table;
    private FormCreationLexer lexer;
    private List<ErrorToken> errorList;

    // CONSTRUCTOR METHOD ------------------------------------------------------
    /**
     * Lexer and parser connection and error list connection
     */
    public CreationFormParser(FormCreationLexer lexer){
        super(lexer);
        
        this.table = lexer.getTable();
        this.errorList = lexer.getLexicalErrors();
    }

    // OVERRIDE METHODS --------------------------------------------------------
    @Override
    public void report_error(String message, Object info) {
        try{
            Symbol cur_token = (Symbol) info;

            StringBuilder builder= new StringBuilder();

            builder.append("Symbol: ");
            builder.append(symbl_name_from_id(cur_token.sym));
            
            if(cur_token != null){
                builder.append(", Lexeme: ");
                builder.append(cur_token.value);
            }

            if(message != null){
                builder.append(", Info: ");
                builder.append(message);
            }
            
            errorList.add(new ErrorToken(
                cur_token.value.toString(),// Lexeme?
                builder.toString(),
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));

        } catch (Exception e){
           System.out.println("Erroooooooooooooooor");
        }
    }

    @Override
    public void syntax_error(Symbol cur_token) {
        System.err.println("Unexpected token at line " 
            + cur_token.left + ", column " + cur_token.right);

        StringBuilder mssBuilder = new StringBuilder();

        String lexeme = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        mssBuilder.append(symbl_name_from_id(cur_token.sym)+" ");
        
        if(cur_token.value != null) {
            mssBuilder.append(cur_token.value.toString());
        }

        mssBuilder.append(", line: ");
        mssBuilder.append(cur_token.left);
        mssBuilder.append(", col: ");
        mssBuilder.append(cur_token.right);
        
        if( expected_token_ids().isEmpty()  ){
            mssBuilder.append(" -- ya no se esperaba ningun simbolo");
        } else {
            mssBuilder.append("Se esperaba: ");
            for(Integer expected_token_id : expected_token_ids() ){ 
                if(!symbl_name_from_id(expected_token_id).equals("error")){
                    mssBuilder.append(symbl_name_from_id(expected_token_id));
                    mssBuilder.append(" ");
                }
            }
        }

            errorList.add(new ErrorToken(
                lexeme,
                mssBuilder.toString(),
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));

        System.err.println(mssBuilder.toString() + " in line: " + cur_token.left);
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token){
        System.out.println("Tronó, ya perdíste");
        String lexeme = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);

           errorList.add(new ErrorToken(
                lexeme,
                "Unrecovered error :(",
                ErrorType.SYNTACTIC,
                cur_token.left,
                cur_token.right
            ));
    }


    // GETTERS -----------------------------------------------------------------
    public FormCreationLexer getLexer(){
        return this.lexer;
    }

    public SymbolTable getTable(){
        return this.table;
    }    

    public List<ErrorToken> getErrorList(){
        return this.errorList;
    }

:};

/********************************* TERMINALS **********************************/
    terminal
            // CODE BLOCKS
            IF, ELSE_IF, ELSE,
            WHILE, DO, FOR,

            // RESERVED WORDS TO VARIABLES
            NUMBER_VARIABLE, STRING_VARIABLE, SPECIAL_VARIABLE,

            DRAW,

            // COLOR
            COLOR_VALUE,

            // ELEMENT ATTRIBUTES
            WIDTH, HEIGHT,

            // ARITHMETIC OPERATORS
            PLUS, MINUS, MULTIPLY, DIVIDE, EXPO, MODULE,

            // RELATIONSHIP OPERATORS
            EQUAL, DIFERENT, GOE, LOE, GREATER, LESS, ASSIGN,

            // LOGIC OPERATORS
            AND, OR, NOT,

            // GROUPING SYMBOLS
            OPEN_PARENT, CLOSED_PARENT,
            OPEN_SQR_BRACKETS, CLOSED_SQR_BRACKETS,
            OPEN_CURLY_BRACKETS, CLOSED_CURLY_BRACKETS,

            // PUNCTUATION SYMBOLS
            DOT, COMMA, TWO_POINTS, 
            
            // EXTRAS
            SEMICOLON, IN,RANGE,

            // SECTIONS
            SECTION,
            POINT_X, POINT_Y, ORIENTATION,
            VERTICAL, HORIZONTAL,
            ELEMENTS,

            // TABLE
            TABLE,

            // TEXT
            TEXT, CONTENT,

            // STYLES
            STYLES, COLOR, BACKGROUND_COLOR, TEXT_SIZE,
            FONT_FAMILY,MONO, SANS_SERIF, CURSIVE,
            BORDER, LINE_BORDER, DOTTED_BORDER, DOUBLE_BORDER,

            // QUESTIONS
            LABEL, QUESTION, OPEN_QUESTION, DROP_QUESTION,
            SELECT_QUESTION, MULTIPLE_QUESTION,
            OPTIONS,
            FIRST, SECOND, THIRD, FOURTH, FIFTH,
            CORRECT,
            WHO_IS_THAT_POKEMON,

            // EMOJIS
            SMILE, SAD, SERIOUS, HEART, STAR, STAR_NUMBER, CAT

    ;
    
terminal Integer INTEGER;
terminal Double NUMBER;
terminal String STRING;
terminal String IDENTIFIER;


/******************************** NO TERMINALS ********************************/

    non terminal Node
                pkm_forms,
                start_stmt_list, start_stmt,
    
                // VARIABLES
                var_declaration, var_initialization, var_assignment,
                special_var, open_special_question, q_attributes, attributes, draw_call, arg_list,
                // STYLE
                style, border_attr,
                text_body,
                content,
                general_string,
                general_text,
                // SECTIONS
                section, section_body, base_attributes, opt_orientation, orientation_val, opt_elements, opt_styles, style_list,
                    // ELEMENTS
                    elements, element_list, element,
                // TABLES
                table, table_body, table_elements, row_list, row, cell_list, cell,
                // TEXT ELEMENT
                text,
                // QUESTIONS
                open_question, oq_body, opt_width, opt_height, label, 
                drop_question, dq_body, options, dq_options,
                select_question, sq_body,
                multiple_question, mq_body, opt_correct_list, correct_values, opt_correct,

                who_is_that_pokemon,
                // CODE BLOCKS
                block, stmt_list, stmt,
                    // IF
                    if_stmt,

                    // IF-ELSE
                    else_if_list,
                    else_if,
                    // ELSE
                    else_opt,
                    // WHILE
                    while_stmt,
                    // DO-WHILE
                    do_while_stmt,
                    // FOR 
                    for_stmt,
                    for_init,
                    for_update,
                    for_in_stmt
    ;

non terminal Node logic_expr;
non terminal Node arithmetic_expr;

/********************************* PRECEDENCE *********************************/

precedence left OR, AND;
precedence right NOT;

precedence nonassoc EQUAL, DIFERENT, GREATER, LESS, GOE, LOE;

precedence left PLUS, MINUS;
precedence left MULTIPLY, DIVIDE;
precedence left EXPO, MODULE;

precedence left ELSE;
precedence left ELSE_IF;

/********************************** GRAMMAR ***********************************/


    start with pkm_forms;

    pkm_forms ::= start_stmt_list:s {:
            Node node = new Node(NodeType.PROGRAM);
            node.addChild(s);
            RESULT = node;
        :}
    ;

    start_stmt_list ::= start_stmt_list:l start_stmt:s {:
            l.addChild(s);
            RESULT = l;
        :}
        | start_stmt:s {:
            Node node = new Node(NodeType.STMT_LIST);
            node.addChild(s);
            RESULT = node;
        :}
    ;

    start_stmt ::= var_declaration:v    {: RESULT = v; :}
        | var_initialization:v          {: RESULT = v; :}
        | var_assignment:v              {: RESULT = v; :}
        | section:v                     {: RESULT = v; :}
        | table:v                       {: RESULT = v; :}
        | text:v                        {: RESULT = v; :}
        | open_question:v               {: RESULT = v; :}
        | drop_question:v               {: RESULT = v; :}
        | select_question:v             {: RESULT = v; :}
        | multiple_question:v           {: RESULT = v; :}
        | special_var:v                 {: RESULT = v; :}
        | draw_call:v                   {: RESULT = v; :}
        | if_stmt:v                     {: RESULT = v; :}
        | while_stmt:v                  {: RESULT = v; :}
        | do_while_stmt:v               {: RESULT = v; :}
        | for_stmt:v                    {: RESULT = v; :}
        | for_in_stmt:v                 {: RESULT = v; :}
    ;

    // ARITHMETIC EXPRESIONS
    arithmetic_expr ::= arithmetic_expr:e1 PLUS arithmetic_expr:e2 {:
            
            Node node = new Node(NodeType.ADD, null);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
    
        | arithmetic_expr:e1 MINUS arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.SUB);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 MULTIPLY arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.MUL);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 DIVIDE arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.DIV);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 EXPO arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.POW);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 MODULE arithmetic_expr:e2 {:
            
            Node node = new Node(NodeType.MOD);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
        // UNITY OPERATION
        | MINUS arithmetic_expr:e {:
        
            Node node = new Node(NodeType.NEG);
            node.addChild(e);
            
            RESULT = node;
        :}

        | PLUS arithmetic_expr:e {:
        
            Node node = new Node(NodeType.POS);
            node.addChild(e);
            
            RESULT = node;
        :}
        
        // VALUES
        | INTEGER:i {:
        
            RESULT = new Node(NodeType.NUMBER, i);
        :}

        | NUMBER:d {:
            RESULT = new Node(NodeType.NUMBER, d);
        :}
        
        // VARIABLES
        | IDENTIFIER:id {:
            RESULT = new Node(NodeType.ID, id);
        :}
        | OPEN_PARENT arithmetic_expr:e CLOSED_PARENT {:
            RESULT = e;
        :}
    ;
    
    // LOGIC EXPRESSIONS
    logic_expr ::= arithmetic_expr:e1 GREATER arithmetic_expr:e2 {:

            Node node = new Node(NodeType.GT);
            node.addChild(e1);
            node.addChild(e2);

            RESULT = node;
        :}

        | arithmetic_expr:e1 GOE arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.GE);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
        
        | arithmetic_expr:e1 LESS arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.LT);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 LOE arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.LE);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
        
        | arithmetic_expr:e1 EQUAL arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.EQ);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | arithmetic_expr:e1 DIFERENT arithmetic_expr:e2 {:
        
            Node node = new Node(NodeType.NE);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
        
        // LOGICAL OPETATORS
        | logic_expr:e1 OR logic_expr:e2 {:
        
            Node node = new Node(NodeType.OR);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
        
        | logic_expr:e1 AND logic_expr:e2 {:
        
            Node node = new Node(NodeType.AND);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}

        | NOT logic_expr:e {:
        
            Node node = new Node(NodeType.NOT);
            node.addChild(e);
            
            RESULT = node;
        :}
        
        // PARENTENCES
        | OPEN_PARENT logic_expr:e CLOSED_PARENT {:
            RESULT = e;
        :}
    ;
    

    // VARIABLE DECLARATION
    var_declaration ::= NUMBER_VARIABLE IDENTIFIER:id {: // number x

            Node node = new Node(NodeType.VAR_DECLARATION, null);

            node.addChild(new Node(NodeType.TYPE_NUMBER, null)); //number
            node.addChild(new Node(NodeType.ID, id)); //x

            RESULT = node;
        :}
        | STRING_VARIABLE IDENTIFIER:id {: // string name

            Node node = new Node(NodeType.VAR_DECLARATION, null);

            node.addChild(new Node(NodeType.TYPE_STRING, null)); //string
            node.addChild(new Node(NodeType.ID, id)); //name

            RESULT = node;
        :}
    ;

    // VARIABLE INITIALIZATION
    var_initialization ::= NUMBER_VARIABLE IDENTIFIER:id ASSIGN arithmetic_expr:e {: // number myHeight = 20.10

            Node node = new Node(NodeType.VAR_INITIALIZATION, null);

            node.addChild(new Node(NodeType.TYPE_NUMBER, null)); // number
            node.addChild(new Node(NodeType.ID, id)); // myHeight
            node.addChild(new Node(NodeType.ASSIGN, null)); // =
            node.addChild(e); // 20.10

            table.assignValueToVariable(id,e.getValue());

            RESULT = node;
        :}
        | STRING_VARIABLE IDENTIFIER:id ASSIGN general_string:s {: // string name = "Toribio"

            Node node = new Node(NodeType.VAR_INITIALIZATION, null);

            node.addChild(new Node(NodeType.TYPE_STRING, null)); // string
            node.addChild(new Node(NodeType.ID, id)); // name
            node.addChild(new Node(NodeType.ASSIGN, null)); // =
            node.addChild(s); // "Toribio"

            table.assignValueToVariable(id,s.getValue());

            RESULT = node;

        :}
    ;

    // VARIABLE ASIGNATION
    var_assignment ::= IDENTIFIER:id ASSIGN arithmetic_expr:e {: // x = 10
            
            Node node = new Node(NodeType.VAR_ASSIGNMENT, null);
            
            node.addChild(new Node(NodeType.ID, id)); // x
            node.addChild(new Node(NodeType.ASSIGN, null)); // = 
            node.addChild(e); // 10

            table.assignValueToVariable(id,e.getValue());
            
            RESULT = node;
        :}
        |IDENTIFIER:id ASSIGN general_string:s {: // x = "PEPE"
            
            Node node = new Node(NodeType.VAR_ASSIGNMENT, null);
            
            node.addChild(new Node(NodeType.ID, id)); // x
            node.addChild(new Node(NodeType.ASSIGN, null)); // = 
            node.addChild(s); // 10
            
            table.assignValueToVariable(id,s.getValue());

            RESULT = node;
            
        :}
    ;

    // SPECIAL VARIABLE
    special_var ::= SPECIAL_VARIABLE IDENTIFIER:id ASSIGN open_special_question:oq {:
    
            Node node = new Node(NodeType.SPECIAL_INIT);// special
            node.addChild(new Node(NodeType.ID, id));// myQuestion
            node.addChild(oq);
            
            RESULT = node;
        :}
    ;
    
    open_special_question ::= OPEN_QUESTION OPEN_SQR_BRACKETS q_attributes:ats CLOSED_SQR_BRACKETS {:
    
            Node node = new Node(NodeType.OPEN_QUESTION);
            node.addChild(ats);
            
            RESULT = node;
    
        :}
    ;

    general_string ::= STRING:str {:
            RESULT = new Node(NodeType.STRING, str);
        :}
    ;

    q_attributes ::= q_attributes:l COMMA attributes:a {:
            l.addChild(a);
            RESULT = l;
        :}
        | q_attributes:l COMMA {:
            RESULT = l;
        :}
        | attributes:a {:
            Node node = new Node(NodeType.ATTR_LIST);
            node.addChild(a);
            RESULT = node;
        :}
    ;

    attributes ::= WIDTH TWO_POINTS arithmetic_expr:e {:
            Node node = new Node(NodeType.ATTR, "width");
            node.addChild(e);
            RESULT = node;
        :}

        | HEIGHT TWO_POINTS arithmetic_expr:e {:
            Node node = new Node(NodeType.ATTR, "height");
            node.addChild(e);
            RESULT = node;
        :}

        | LABEL TWO_POINTS general_string: g{:
            Node node = new Node(NodeType.ATTR, "label");
            node.addChild(g);
            RESULT = node;
        :}
        | WIDTH TWO_POINTS QUESTION {:
            Node node = new Node(NodeType.ATTR, "width");
            node.addChild(new Node(NodeType.PLACEHOLDER));
            RESULT = node;
        :}

        | HEIGHT TWO_POINTS QUESTION {:
            Node node = new Node(NodeType.ATTR, "height");
            node.addChild(new Node(NodeType.PLACEHOLDER));
            RESULT = node;
        :}

        | LABEL TWO_POINTS QUESTION {:
            Node node = new Node(NodeType.ATTR, "label");
            node.addChild(new Node(NodeType.PLACEHOLDER));
            RESULT = node;
        :}
    ;

    draw_call ::= IDENTIFIER:id DOT DRAW OPEN_PARENT arg_list:a CLOSED_PARENT {:
            Node node = new Node(NodeType.DRAW_CALL);
            node.addChild(new Node(NodeType.ID, id));
            node.addChild(a);
            RESULT = node;
        :}
    ;

    arg_list ::= arg_list:l COMMA arithmetic_expr:e {:
            l.addChild(e);
            RESULT = l;
        :}

        | arithmetic_expr:e {:
            Node node = new Node(NodeType.ARG_LIST);
            node.addChild(e);
            RESULT = node;
        :}
        | {:
            RESULT = new Node(NodeType.ARG_LIST);
        :}
    ;


    // GENERAL TEXT
    general_text ::= STRING:str {:
            
            Node node = new Node(NodeType.STRING, str);
            
            RESULT = node;
        :}
    ;

    // SECTION
    section ::= SECTION OPEN_SQR_BRACKETS section_body:sb CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.SECTION);
            node.addChild(sb);
            RESULT = node;
        :}
    ;

    section_body ::= base_attributes:b opt_orientation:o opt_elements:e opt_styles:s {:
            Node node = new Node(NodeType.SECTION_BODY);
            node.addChild(b);
            if (o != null) {
                node.addChild(o);
            }
            if (e != null){
                node.addChild(e);
            } 
            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;

    base_attributes ::= 
            WIDTH TWO_POINTS arithmetic_expr:w COMMA
            HEIGHT TWO_POINTS arithmetic_expr:h COMMA
            POINT_X TWO_POINTS arithmetic_expr:px COMMA
            POINT_Y TWO_POINTS arithmetic_expr:py COMMA
        {:
            Node node = new Node(NodeType.ATTR_LIST);

            Node wNode = new Node(NodeType.ATTR, "width"); 
            wNode.addChild(w);
            
            Node hNode = new Node(NodeType.ATTR, "height");
            hNode.addChild(h);
            
            Node pxNode = new Node(NodeType.ATTR, "pointX");
            pxNode.addChild(px);
            
            Node pyNode = new Node(NodeType.ATTR, "pointY");
            pyNode.addChild(py);

            node.addChild(wNode);
            node.addChild(hNode);
            node.addChild(pxNode);
            node.addChild(pyNode);

            RESULT = node;
        :}
    ;

    opt_orientation ::= ORIENTATION TWO_POINTS orientation_val:o COMMA {:
            Node node = new Node(NodeType.ORIENTATION);
            node.addChild(o);
            RESULT = node;
        :}
    | /* EMPTY */ {:
            RESULT = null; 
        :}
    ;

    orientation_val ::= VERTICAL {:
            RESULT = new Node(NodeType.VERTICAL);
        :}
        | HORIZONTAL {:
            RESULT = new Node(NodeType.HORIZONTAL);
        :}
    ;

    opt_elements ::= ELEMENTS TWO_POINTS OPEN_CURLY_BRACKETS element_list:l CLOSED_CURLY_BRACKETS COMMA {:
            Node node = new Node(NodeType.ELEMENTS);
            node.addChild(l);
            RESULT = node;
        :}
        | /* EMPTY */ {:
            RESULT = null;
        :}
    ;
/****************************INCOMPLETE****************************************/
    element_list ::= element_list:l COMMA element:e {:
            l.addChild(e);
            RESULT = l;
        :}
        | element:e {:
            Node node = new Node(NodeType.ELEMENT_LIST);
            node.addChild(e);
            RESULT = node;
        :}
    ;

    opt_styles ::= STYLES OPEN_SQR_BRACKETS style_list:s CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.STYLE_BLOCK);
            node.addChild(s);
            RESULT = node;
        :}
        | /* EMPTY */ {:
            RESULT = null;
        :}
    ;

    style_list ::= style_list:l COMMA style:s {:
            l.addChild(s);
            RESULT = l;
        :}
        | style:s {:
            Node node = new Node(NodeType.STYLE_BLOCK);
            node.addChild(s);
            RESULT = node;
        :}
    ;

    style ::= COLOR TWO_POINTS COLOR_VALUE:c {:
            Node node = new Node(NodeType.COLOR_STYLE, "color");
            node.addChild(new Node(NodeType.COLOR_VALUE, c));
            RESULT = node;
        :}
        | BACKGROUND_COLOR TWO_POINTS COLOR_VALUE:c {: 
            Node node = new Node(NodeType.BACKGROUND_COLOR_STYLE, "backgroud_color");
            node.addChild(new Node(NodeType.BACKGROUND_COLOR, c));
            RESULT = node;
        :}
        | TEXT_SIZE TWO_POINTS arithmetic_expr:e {:
            Node node = new Node(NodeType.TEXT_SIZE_STYLE, "text_size");
            node.addChild(new Node(NodeType.TEXT_SIZE,e));
            RESULT = node;
        :}
        | FONT_FAMILY TWO_POINTS MONO {:
            Node node = new Node(NodeType.FONT_FAMILY_STYLE, "text_size");
            node.addChild(new Node(NodeType.FONT_FAMILY, "mono"));
            RESULT = node;
        :}
        | FONT_FAMILY TWO_POINTS SANS_SERIF {:
            Node node = new Node(NodeType.FONT_FAMILY_STYLE, "text_size");
            node.addChild(new Node(NodeType.FONT_FAMILY, "sans_serif"));
            RESULT = node;
        :}
        | FONT_FAMILY TWO_POINTS CURSIVE {:
            Node node = new Node(NodeType.FONT_FAMILY_STYLE, "text_size");
            node.addChild(new Node(NodeType.FONT_FAMILY, "cursive"));
            RESULT = node;
        :}
        | BORDER TWO_POINTS OPEN_PARENT border_attr:b CLOSED_PARENT{: 
            Node node = new Node(NodeType.BORDER);
            node.addChild(b);
            RESULT = node;
        :}
    ;

    border_attr ::= NUMBER:e COMMA LINE_BORDER COMMA COLOR_VALUE:c {:
            Node node = new Node(NodeType.BORDER_ATTR);
            node.addChild(new Node(NodeType.NUMBER, e));
            node.addChild(new Node(NodeType.LINE_BORDER, "line_border"));
            node.addChild(new Node(NodeType.COLOR_VALUE, c));
            RESULT = node;
        :}
        | NUMBER:e COMMA DOTTED_BORDER COMMA COLOR_VALUE:c {:
            Node node = new Node(NodeType.BORDER_ATTR);
            node.addChild(new Node(NodeType.NUMBER, e));
            node.addChild(new Node(NodeType.DOTTED_BORDER, "dotted_border"));
            node.addChild(new Node(NodeType.COLOR_VALUE, c));
            RESULT = node;
        :}
        | NUMBER:e COMMA DOUBLE_BORDER COMMA COLOR_VALUE:c {:
            Node node = new Node(NodeType.BORDER_ATTR);
            node.addChild(new Node(NodeType.NUMBER, e));
            node.addChild(new Node(NodeType.DOUBLE_BORDER, "double_border"));
            node.addChild(new Node(NodeType.COLOR_VALUE, c));
            RESULT = node;
        :}
    ;

    // TABLES
    table ::= TABLE OPEN_SQR_BRACKETS table_body:tb CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.TABLE);
            node.addChild(tb);
            RESULT = node;
        :}
    ;

    table_body ::= base_attributes:b table_elements:e opt_styles:s {:
            Node node = new Node(NodeType.TABLE);
            node.addChild(b);
            node.addChild(e);

            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;

    table_elements ::= ELEMENTS TWO_POINTS OPEN_CURLY_BRACKETS row_list:r CLOSED_CURLY_BRACKETS COMMA {:
            Node node = new Node(NodeType.TABLE_ELEMENTS);
            node.addChild(r);
            RESULT = node;
        :}
    ;

    row_list ::= row_list:l COMMA row:r {:
            l.addChild(r);
            RESULT = l;
        :}
        | row:r
        {:
            Node node = new Node(NodeType.TABLE_ELEMENTS);
            node.addChild(r);
            RESULT = node;
        :}
    ;

    row ::= OPEN_SQR_BRACKETS cell_list:c CLOSED_SQR_BRACKETS
        {:
            Node node = new Node(NodeType.ROW);
            node.addChild(c);
            RESULT = node;
        :}
    ;

    cell_list ::= cell_list:l COMMA cell:c {:
            l.addChild(c);
            RESULT = l;
        :}
        | cell:c {:
            Node node = new Node(NodeType.ROW);
            node.addChild(c);
            RESULT = node;
        :}
    ;
    
    cell ::= OPEN_CURLY_BRACKETS element:e CLOSED_CURLY_BRACKETS {:
            Node node = new Node(NodeType.CELL);
            node.addChild(e);
            RESULT = node;
        :}
    ;


    element ::= section:s {:
            RESULT = s;
        :}
        | special_var:sp {:
            RESULT = sp;
        :}
        | draw_call:d {:// ? Hmm
            RESULT = d;
        :}
        | table:t {:
            RESULT = t;
        :}
        | text:tx {:
            RESULT = tx;
        :}
        | open_question:v {:
            RESULT = v;
        :}
        | drop_question:v {: 
            RESULT = v; 
        :}
        | select_question:v {: 
            RESULT = v;
        :}
        | multiple_question:v {:
            RESULT = v;
        :}
    ;

    // TEXT ELEMENT
    text ::= TEXT OPEN_SQR_BRACKETS text_body:tb CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.TEXT);
            node.addChild(tb);
            RESULT = node;
        :}
    ;
    
    text_body ::= opt_width:w opt_height:h content:c opt_styles:s {:
            Node node = new Node(NodeType.TEXT_BODY);

            if (w != null) {
                node.addChild(w);
            }
            if (h != null) {
                node.addChild(h);
            }

            node.addChild(c);

            if (s != null){
                node.addChild(s);
            } 

            RESULT = node;
        :}
    ;
    
    opt_width ::= WIDTH TWO_POINTS arithmetic_expr:e COMMA {:
            Node node = new Node(NodeType.ATTR, "width");
            node.addChild(e);
            RESULT = node;
        :}
        | /* EMPTY */ {: 
            RESULT = null;
        :}
    ;

    opt_height ::= HEIGHT TWO_POINTS arithmetic_expr:e COMMA {:
            Node node = new Node(NodeType.ATTR, "height");
            node.addChild(e);
            RESULT = node;
        :}
        | /* EMPTY */ {: 
            RESULT = null;
        :}
    ;

    content ::= CONTENT TWO_POINTS general_text:s {:
            Node node = new Node(NodeType.CONTENT);
            node.addChild(s);
            RESULT = node;
        :}
    ;
    
    // QUESTIONS
        // OPEN QUESTIONS
    open_question ::= OPEN_QUESTION OPEN_SQR_BRACKETS oq_body:b CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.OPEN_QUESTION);
            node.addChild(b);
            RESULT = node;
        :}
    ;

    oq_body ::= opt_width:w opt_height:h label:l opt_styles:s {:
            Node node = new Node(NodeType.OPEN_QUESTION);

            if (w != null) {
                node.addChild(w);
            }
            if (h != null) {
                node.addChild(h);
            }

            node.addChild(l);

            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;

    label ::= LABEL TWO_POINTS general_text:s COMMA {:
            Node node = new Node(NodeType.LABEL);
            node.addChild(s);
            RESULT = node;
        :}
    ;

        // DROP QUESTION
    drop_question ::= DROP_QUESTION OPEN_SQR_BRACKETS dq_body:d CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.DROP_QUESTION);
            node.addChild(d);
            RESULT = node;
        :}
    ;
    
    dq_body ::= opt_width:w opt_height:h label:l options:op opt_correct:c opt_styles:s {:
            Node node = new Node(NodeType.DROP_QUESTION);

            if (w != null) {
                node.addChild(w);
            }
            if (h != null) {
                node.addChild(h);
            }

            node.addChild(l);
            node.addChild(op);

            if(c!=null){
                node.addChild(c);
            }
            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;
    
    options ::= OPTIONS TWO_POINTS OPEN_CURLY_BRACKETS dq_options:dq CLOSED_CURLY_BRACKETS COMMA {:
            Node node = new Node(NodeType.OPTIONS);
            node.addChild(dq);
            RESULT = node;
        :}
        | OPTIONS TWO_POINTS who_is_that_pokemon:w COMMA {:
            Node node = new Node(NodeType.OPTIONS);
            node.addChild(w);
            RESULT = node;
        :}
    ;
    
    dq_options ::= dq_options:l COMMA general_text:g {:
            l.addChild(g);
            RESULT = l;
        :}
        | general_text:g
        {:
            Node node = new Node(NodeType.OPTION_LIST);
            node.addChild(g);
            RESULT = node;
        :}
    ;

        // SELECT QUESTION
    select_question ::= SELECT_QUESTION OPEN_SQR_BRACKETS sq_body:d CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.SELECT_QUESTION);
            node.addChild(d);
            RESULT = node;
        :}
    ;
    
    sq_body ::= opt_width:w opt_height:h label:l options:op opt_correct:c opt_styles:s {:
            Node node = new Node(NodeType.SELECT_QUESTION);

            if (w != null) {
                node.addChild(w);
            }
            if (h != null) {
                node.addChild(h);
            }

            node.addChild(l);
            node.addChild(op);

            if(c!=null){
                node.addChild(c);
            }
            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;
        
        // MULTIPLE QUESTION
    multiple_question ::= MULTIPLE_QUESTION OPEN_SQR_BRACKETS mq_body:d CLOSED_SQR_BRACKETS {:
            Node node = new Node(NodeType.MULTIPLE_QUESTION);
            node.addChild(d);
            RESULT = node;
        :}
    ;
    
    mq_body ::= opt_width:w opt_height:h label:l options:op opt_correct_list:c opt_styles:s {:
            Node node = new Node(NodeType.MULTIPLE_QUESTION);
            if (w != null) {
                node.addChild(w);
            }
            if (h != null) {
                node.addChild(h);
            }

            node.addChild(l);
            node.addChild(op);

            if(c!=null){
                node.addChild(c);
            }
            if (s != null) {
                node.addChild(s);
            }

            RESULT = node;
        :}
    ;
    
    opt_correct_list ::= CORRECT TWO_POINTS OPEN_CURLY_BRACKETS correct_values:co CLOSED_CURLY_BRACKETS COMMA {:
            Node node = new Node(NodeType.CORRECT_LIST);
            node.addChild(co);
            RESULT = node;
        :}
        | /* EMPTY */ {: 
            RESULT = null;
        :}
    ;
    
    correct_values ::= correct_values:l COMMA arithmetic_expr:e {:
            l.addChild(e);
            RESULT = l;
        :}
        | arithmetic_expr:e {:
            Node node = new Node(NodeType.VALUE_LIST);
            node.addChild(e);
            RESULT = node;
        :}
    ;
    
    opt_correct ::= CORRECT TWO_POINTS arithmetic_expr:e COMMA {:
            Node node = new Node(NodeType.CORRECT);
            node.addChild(e);
            RESULT = node;
        :}
        | /* EMPTY */ {:
            RESULT = null; 
        :}
    ;


        // POKEMON
    who_is_that_pokemon ::= WHO_IS_THAT_POKEMON OPEN_PARENT NUMBER 
            COMMA arithmetic_expr:e1 COMMA arithmetic_expr:e2 CLOSED_PARENT {:
            Node node = new Node(NodeType.WHO_IS_THAT_POKEMON);
            node.addChild(e1);
            node.addChild(e2);
            
            RESULT = node;
        :}
    ;

    // CODE BLOCKS
    block ::= OPEN_CURLY_BRACKETS stmt_list:s CLOSED_CURLY_BRACKETS {:
            Node node = new Node(NodeType.BLOCK);
            node.addChild(s);
            RESULT = node;
        :}
    ;
        
    stmt_list ::= stmt_list:l stmt:s {:
            l.addChild(s);
            RESULT = l;
        :}
        | stmt:s {:
            Node node = new Node(NodeType.STMT_LIST);
            node.addChild(s);
            RESULT = node;
        :}
    ;
    
    stmt ::= var_declaration:v          {: RESULT = v; :}
        | var_assignment:v              {: RESULT = v; :}
        | open_question:v               {: RESULT = v; :}
        | drop_question:v               {: RESULT = v; :}
        | select_question:v             {: RESULT = v; :}
        | multiple_question:v           {: RESULT = v; :}
        | section:v                     {: RESULT = v; :}
        | table:v                       {: RESULT = v; :}
        | text:v                        {: RESULT = v; :}
        | if_stmt:v                     {: RESULT = v; :}
        | while_stmt:v                  {: RESULT = v; :}
        | do_while_stmt:v               {: RESULT = v; :}
        | for_stmt:v                    {: RESULT = v; :}
        | for_in_stmt:v                 {: RESULT = v; :}
    ;

    // IF
    if_stmt ::= IF OPEN_PARENT logic_expr:c CLOSED_PARENT block:b else_if_list:e else_opt:o {:
            Node node = new Node(NodeType.IF);

            node.addChild(c);
            node.addChild(b);

            if (e != null) {
                node.addChild(e);
            }
            if (o != null) {
                node.addChild(o);
            }

            RESULT = node;
        :}
    ;
    
    // IF-ELSE
    else_if_list ::= else_if_list:l else_if:e {:
            l.addChild(e);
            RESULT = l;
        :}
        | else_if:e {:
            Node node = new Node(NodeType.ELSE_IF);
            node.addChild(e);
            RESULT = node;
        :} | /* EMPRY */ {:
            RESULT = null;
        :}
    ;
    
    else_if ::= ELSE_IF OPEN_PARENT logic_expr:c CLOSED_PARENT block:b {:
            Node node = new Node(NodeType.ELSE_IF);
            node.addChild(c);
            node.addChild(b);
            RESULT = node;
        :}
    ;
    
    // ELSE
    else_opt ::= ELSE block:b
        {:
            Node node = new Node(NodeType.ELSE);
            node.addChild(b);
            RESULT = node;
        :}
        | /* EMPYTY */ {:
            RESULT = null; 
        :}
    ;

    
    // WHILE
    while_stmt ::= WHILE OPEN_PARENT logic_expr:c CLOSED_PARENT block:b {:
            Node node = new Node(NodeType.WHILE);
            node.addChild(c);
            node.addChild(b);
            RESULT = node;
        :}
    ;

    // DO-WHILE
    do_while_stmt ::= DO block:b WHILE OPEN_PARENT logic_expr:c CLOSED_PARENT {:
            Node node = new Node(NodeType.DO_WHILE);
            node.addChild(b);
            node.addChild(c);
            RESULT = node;
        :}
    ;
    // FOR
    for_stmt ::= FOR OPEN_PARENT for_init:i SEMICOLON logic_expr:c SEMICOLON for_update:u CLOSED_PARENT block:b {:
            Node node = new Node(NodeType.FOR);

            node.addChild(i);
            node.addChild(c);
            node.addChild(u);
            node.addChild(b);

            RESULT = node;
        :}
    ;
    
    for_init ::= IDENTIFIER:id ASSIGN arithmetic_expr:e {:
            Node node = new Node(NodeType.INIT);
            node.addChild(new Node(NodeType.ID, id));
            node.addChild(e);
            RESULT = node;
        :}
    ;
    
    for_update ::= IDENTIFIER:id ASSIGN arithmetic_expr:e {:
            Node node = new Node(NodeType.UPDATE);
            node.addChild(new Node(NodeType.ID, id));
            node.addChild(e);
            RESULT = node;
        :}
    ;

    for_in_stmt ::= FOR OPEN_PARENT IDENTIFIER:id IN arithmetic_expr:start RANGE arithmetic_expr:end CLOSED_PARENT block:b {:
            Node node = new Node(NodeType.FOR_RANGE);

            node.addChild(new Node(NodeType.ID, id));
            node.addChild(start);
            node.addChild(end);
            node.addChild(b);

            RESULT = node;
        :}
    ;